#!/opt/homebrew/bin/python3

import os
import json

def rename_yabai():
    data_list = json.loads(os.popen('yabai -m query --spaces').read())
    for item in data_list:
        print(f"{item['index']} | {item['label']}")
    index = input("What display name to change\n")
    name = input("What's the new label?\n")

    stream = os.popen(f'yabai -m space {index} --label {name}')
    print('Label applied') if stream else print(stream)



if __name__ == "__main__":
    rename_yabai()
