#!/opt/homebrew/bin/python3

import os
import json
import argparse

def rename_yabai():
    display_yabai_displays()
    index = input("What display name to change\n")
    name = input("What's the new label?\n")

    stream = os.popen(f'yabai -m space {index} --label {name}')
    print('Label applied') if stream else print(stream)

def display_yabai_displays() -> None:
    """
    Shows a list of yabai's screens to stdout
    
    Format:
    <index> | <label>
    ...
    """
    data_list = json.loads(os.popen('yabai -m query --spaces').read())
    for item in data_list:
        print(f"{item['index']} | {item['label']}") 

def switch_yabai_displays(name: str, index: int) -> None:
    stream = os.popen(f'yabai -m space --focus {index}')

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument('command', choices=['display', 'rename', 'switch'], type=str)
    # Display, Rename, Switch
    #TODO: Write ArgParse Docs

    args = parser.parse_args()

    match args.command:
        case 'display':
            display_yabai_displays()
        case 'rename':
            rename_yabai()
        case 'switch':
            print('world')

